# Este flujo de trabajo realizará una instalación limpia de las dependencias de Node,
# cacheará/restaurará las mismas, compilará el código fuente y ejecutará pruebas en Node.js 20.

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # Ver la tabla de versiones soportadas de Node.js en https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: website/package-lock.json

    - name: Install dependencies and build project
      run: |
        cd website
        ls -al
        if [ ! -f package-lock.json ]; then
          npm install
        fi
        npm ci
        npm run build --if-present
        npm test --no-watch --no-progress --browser=ChromeHeadLess
